### ISSUE TITLE
directory path for apps seems redundant

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#16]
Apps are located on the site under the path e..g

Home -> Apps -> Apps -> World Ocean Simulation System

instead of

Home -> Apps -> World Ocean Simulation System

Is this a directory structure that needs adjusted?

**Comment by tomhenderson** [comment]
![directory-structure](https://user-images.githubusercontent.com/402771/29365963-7cf31bd4-824d-11e7-80e1-eb0253833800.png)

**Comment by abhijithanilkumar** [comment]
By Default, Django organizes different modules as apps. So, basically, the Home->Apps-> point to all the Django apps. And Home->Apps->Apps-> point to the Apps in the appstore. This is because we named our module as 'App'. So there isn't much that we can do here. The best thing possible will be to rename 'App' to something like 'Module'.
